## Instructions

Answer the following questions. It behooves you to answer as much of each question as possible to receive some partial credit. You are advised to begin this lab early so that you have ample time to complete it. **Make sure that your code is commented appropriately to receive full credit on each problem**

## Assignment

This assignment is worth 100 points. There are three sections to this homework assignment: a Fundamentals section, an Essentials section, and an Advanced section. You have all of the tools you need to complete all of the lab, but it is triaged for you to give you an idea of what you should focus on first.

### Fundamentals (30 points)

1. (10 points) Discuss three attributes of an array.

  > Answer:

2. (10 points) What does the `np.arange()` function do?

  > Answer: 

3. (10 points) What is the difference between a shallow and a deep copy in Python? Does Python automatically create deep copies or shallow copies for arrays?

> Answer:

### Essentials (50 points)

4. (10 points) Create a 2x10 array filled with zeros.

In [4]:
## Answer:
import numpy as np

arr = np.array([[0,0,0,0,0,0,0,0,0,0] , [0,0,0,0,0,0,0,0,0,0]])
print(arr)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


5. (10 points) Create a 100 x 100 array where each element is randomly assigned a 1 or 0. Call this matrix `rand`.

In [23]:
## Answer
import random

rand = np.random.randint(2, size = (100,100))
        
print(rand)

[[0 1 1 ... 0 1 1]
 [0 0 0 ... 0 0 1]
 [1 0 1 ... 0 0 1]
 ...
 [1 1 1 ... 1 0 1]
 [1 0 0 ... 0 0 0]
 [1 1 0 ... 1 0 1]]


6. (15 points) Print out the following elements/subsets:

    + The element in the 3rd row, 1st column.
    + The element inf the 100th row, 100th column.
    + The 10th row.
    + The 11th column.
    + Elements from the 20th row, 50th column to the 36th row, 72 column.

In [30]:
## Answer

print('3rd row, 1st column:',rand[2][0])
print('100th row, 100th column:',rand[99][99])
print('10th row:',rand[9])
print('11th row:',rand[10])
print('20th row:',rand[19])
    
print('50th colomn to 36th row:')
col50toRow36 = []
for x in range(36):
    col50toRow36.append(rand[x][49])
print(col50toRow36)

print('72nd column:')
col72 = []
for x in range(100):
    col72.append(rand[x][71])
print(col72)

3rd row, 1st column: 1
100th row, 100th column: 1
10th row: [1 1 1 0 0 1 1 0 0 0 1 1 1 0 0 1 0 0 1 1 1 1 1 0 1 0 0 0 1 0 1 0 1 1 0 1 1
 1 1 1 0 0 0 1 1 1 1 1 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 1 1 0 1 0 1 1 0 0 1 1
 1 1 0 1 1 1 1 1 1 1 0 0 1 0 1 0 0 0 0 1 0 1 1 1 0 0]
11th row: [1 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 1 1 1 1 1 0 0 1 1 0 0 1 0 0
 1 1 0 1 1 1 1 1 1 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 1 1 1 1 1 0 1 0
 0 0 0 0 0 1 1 1 0 1 1 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0]
20th row: [1 1 1 1 1 0 1 0 1 0 0 0 0 1 0 1 0 1 1 1 1 0 0 1 1 0 0 1 1 0 0 1 0 0 0 1 1
 0 1 0 0 0 1 1 0 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 0 1 0 1 0 0 1 0 0 0 1 1 0 1
 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 1 0 0 0 1]
50th colomn to 36th row:
[1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1]
72nd column:
[0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0

7. (15 points) Reshape the original array to a single row of 10000 elements. Calculate the mean of this new array.

In [33]:
## Answer

newArr = rand.reshape(-1)

total = 0
for x in newArr:
    total += x

print(newArr)
print(total/newArr.size)

[0 1 1 ... 1 0 1]
0.5026


### Advanced (20 points)

8. (20 points) Write a function which calculates the median of all values in an array regardless of its shape. Note: arrays do not have a built in median function. You will have to use the other attributes of an array to make this function.

In [42]:
## Answer

def median(arr):
    """takes a numpy array, flattens,
    then returns the median of the data"""
    
    newArr = arr.reshape(-1)
    np.sort(newArr,None,'mergesort')
    
    return newArr[newArr.size//2]

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(median())

0
